allowBuilds:
  esbuild: true

configDependencies:
  '@pnpm/plugin-better-defaults': 0.3.0
  '@pnpm/plugin-trusted-deps': 0.3.0-2

overrides:
  html-minifier>commander: npm:noop-package@1.0.0
  katex>commander: npm:noop-package@1.0.0
  sass>@parcel/watcher: npm:noop-package@1.0.0
