configDependencies:
  '@pnpm/better-defaults': 0.2.2+sha512-CxhLHXeW4XS/wludrcB9wgfVQmWYP0toYW5W700Aal5O6LK8qZmchvlCd/pRckBmAOWn8vT3AHokuyHvzLUv3A==
  '@pnpm/trusted-deps': 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

overrides:
  html-minifier>commander: npm:noop-package@1.0.0
  katex>commander: npm:noop-package@1.0.0
  sass>@parcel/watcher: npm:noop-package@1.0.0

patchedDependencies:
  feed: patches/feed.patch

pnpmfile: node_modules/.pnpm-config/@pnpm/better-defaults/pnpmfile.cjs
